version: '3.8'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=distributedDeliveryRedis

  mysql:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "order_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "distributedDeliverySql"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
