version: '3.8'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=distributedDeliveryRedis

  mysql:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'orderDb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
