version: '3.8'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=distributedDeliveryRedis

  mysql:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'distributedDeliverySql'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'distributedDeliverySql'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - distributedDeliverySql1:/var/lib/mysql

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "5672:5672"      # Porta per il protocollo AMQP
      - "15672:15672"    # Porta per l'interfaccia di gestione
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend

volumes:
  distributedDeliverySql1:
  rabbitmq_data:

networks:
  backend:
